Plugin ready to review
BohdanLeasoft/Drupal-9-Payment-Plugin pull request #1
Opened 2022-08-29 13:01 UTC by BohdanLeasoft

This is payment plugin for Drupal 9 with Commerce 2 extension

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft requested changes

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Builders/ClientBuilder.php
> +  }
Why it located in ClientBuilder? Looks like it should be placed in OrderBuilder

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Builders/ClientBuilder.php
> +}
Why it located in ClientBuilder? Looks like it should be placed in OrderBuilder

Btw, does we really should provide Client object to an order? (it looks the same as Extra object)

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Builders/CustomerBuilder.php
> +    $phone = null;
I think if we remove this line, the code will work anyway, cause you have this condition: `$phone ?? ''`

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Builders/OrderBuilder.php
> +  public $bankconfig;
OrderBuilder extends CustomerBuilder, CustomerBuilder extends ClientBuilder, ClientBuilder has this property

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Builders/OrderBuilder.php
> +  public $clientBuilder;
I wonder, does we really need this properties? the class extends those classes, so we could use their functions without object entity

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Builders/OrderBuilder.php
> +  }
I see OrderBuilder class as class that only collect order data and assemble the order, and I would place those functions somewhere else like Helper class

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Controller/Webhook.php
> +    $this->clientBuilder = new ClientBuilder();
I think in that plugin architecture we could one of them, cause the first extends the second

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Controller/Webhook.php
> +    $this->bankconfig = new Bankconfig();
builder classes already have this property

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Controller/Webhook.php
> +    $this->clientBuilder = new ClientBuilder();
Looks like property $clientBuilder is useless, it uses only for creating property $client, so what the reason to place it as class property?

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Plugin/Commerce/PaymentGateway/BaseOffsitePaymentGateway.php
> +  protected $bankconfig;
builderRedefiner already has this property

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Plugin/Commerce/PaymentGateway/BaseOffsitePaymentGateway.php
> +  }
could we decrease if-else statements?

probably in case we throw an exception - next code lines won't be invoked so if-else statements could be removed

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Plugin/Commerce/PaymentGateway/BaseOffsitePaymentGateway.php
> +  }
the same thing with if-else, try to to use as less as possible this conditions, cause if statements are bad practice, it signals that we have a problem with structure (code flow, etc)

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/PluginForm/AbstractPayment.php
> +    $this->bankconfig = new Bankconfig();
builderRedefiner has this property

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/PluginForm/AbstractPayment.php
> +        $form = $this->helper->setBanktransferForm($form, $order->toArray());
I would create function for each payment method and invoke it in some way without switch - case

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/PluginForm/AbstractPayment.php
> +    $verifiedTerms = null;
Do we really need this inits? Looks like createOrder func expects that those vars could be null, I think the code could work without them (but it needs to be tested)

2022-09-06 05:05 UTC, Denis-Tsyganok-Leasoft commented on src/Builders/OrderBuilder.php
> +        $this->clientBuilder->getExtraLines()
if we try to redefine getExtraLines() in BuilderRedefiner - it won't be redefined here, cause here we invoke this func using the object of clientBuilder.

2022-09-06 13:50 UTC, tiutiunnykleasoft requested changes
1. Add types for return type of the methods.

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on README.md
> +# Ginger Payment Gateway for Drupal 9 Commerce 2.x,
Should `Ginger` be replaced for some placeholder?

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on commerce_ginger.info.yml
> +name: Ginger Payment Gateway
There is also should be placeholders if this info is shows somewhere

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on commerce_ginger.module
> +function commerce_ginger_mail($key, &$message, $params) {
With only one case we could use early return if the case is not one what we looking for 
```php
if ($key != 'order_mail') return;
// code
```

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on commerce_ginger.permissions.yml
> +  title: 'Administer Ginger Payment Gateway'
If `Administer` is correct label?

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on commerce_ginger.routing.yml
> +    _form: '\Drupal\commerce_ginger\Form\BasicSettingsForm'
Namespace is not in PSR standard, could we refacor it?

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on composer.json
> +{
`composer.lock` is also should be in project!

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Bankconfigs/Bankconfig.php
> +  private $pluginName = 'ems-online-drupal9';
In some files we have labels regarding `Ginger` and there is just `ems` label. Could we make it only with `Ginger` labels if we want to extrapolite in in a future?

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Bankconfigs/Bankconfig.php
> +  private $endpoint = 'https://api.online.emspay.eu';
Better to use ginger endpoint for test purposes as ems endpoint doesnt contains all restriction or cases.

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Bankconfigs/Bankconfig.php
> +    switch ($lang)
Try to avoid using swtich. Especially if there is only 1 case :)

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/ClientBuilder.php
> +namespace Drupal\commerce_ginger\Builders;
Ye, that's namespace is not looking so good by PSR

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/ClientBuilder.php
> +  public $bankconfig;
`banconfig` should have an `private` modificator  to avoid random change it.

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Bankconfigs/Bankconfig.php
> +class Bankconfig
This whole class should be static, because we dont use it as really object. Only as a constant storage.

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Bankconfigs/Bankconfig.php
> +  private $pluginVersion = '1.0.0';
If this and other variables doesn't changes while app running, then it should be const

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/ClientBuilder.php
> +    $this->bankconfig = New Bankconfig();
As i note config should be static

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/ClientBuilder.php
> +  public function createClient()
Could we add return type?

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/CustomerBuilder.php
> +  public function __construct()
Should be removed

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +  public $bankconfig;
Basically we don't need a property linked to config class

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +      foreach ($orderArray['flags'] as $flag) {
as we discussed, `in_array` should work there

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +      if (!empty($order_item)) {
Use early return there, for example : 
```php
if (empty($order_item)) continue;
```

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +      amount: new Amount(floatval($raw_amount)*100),
You could use there `RawCost` to perform valid logic.

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +      amount: new Amount(floatval($raw_amount)*100),
```php
amount: new Amount(new RawCost(floatval($raw_amount))),
```

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +      flags: null,
We don't need to specify flags as null

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +      flags: null,
This field is null by default

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +      status: null,
This field is null by default

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +      id: $payment->getOrderId(),
We can't set id, because this is readOnly property.

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Builders/OrderBuilder.php
> +      description: sprintf("%s: %s", t('Order number'), $payment->getOrderId()),
Add getDescription method to provide override possibility

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Controller/Webhook.php
> +    $payment = $this->orderBuilder->getOrderPaymentByTransactionId($orderId, $entityTypeManager);
I don't think the logic of orderBuilder, by sense, should provide such methods. This method should be in some kind of operations controller, like Client or App

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Controller/Webhook.php
> +      case 'new': if (current($apiOrder->toArray()['transactions'])['payment_method'] == 'bank-transfer') {
use 
```php
$apiOrder->getCurrentTransaction()->getPaymentMethod()->get()
```

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Controller/Webhook.php
> +        return true;
As you don't use return value of this method you can just type 
```php
\\ if you want to exit asap
return; 
```

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/Controller/Webhook.php
> +      case 'completed':
As some cases have identical body, you could accumulate it by this way:
```php
case 'cancelled': case 'expired':
\Drupal::messenger()->addWarning($this->t(sprintf('Your order is %s, please try again later'), $status));
        throw new NeedsRedirectException($this->orderBuilder->getCancelUrl($payment));
        break;
```

2022-09-06 13:50 UTC, tiutiunnykleasoft commented on src/PluginForm/AbstractPayment.php
> +        $form = $this->helper->setBanktransferForm($form, $order->toArray());
You could simply add an interface for payment methods and checks, like that
```php
interface PaymentMethodFormInterface
{
public function prepareForm($args): void
}

class ApplePay extends ... implemented PaymentMethodFormInterface
{
...
public function prepareForm()
{
...
}
...
}

public function buildConfigurationForm(array $form, FormStateInterface $form_state)
{
if ($payment instanceof PaymentMethodFormInterface)
{
$payment->prepareForm();
}  else {
...
}
}
```

2022-09-26 15:49 UTC, Denis-Tsyganok-Leasoft approved these changes
👍

2022-09-26 15:49 UTC, Denis-Tsyganok-Leasoft commented on src/Bankconfig/Bankconfig.php
> +  }
I'd suggest to remove those getter functions and just use Bankconfig::PLUGIN_NAME etc, I don't see any reason to use getter functions, probably you could describe they purpose

2022-09-26 15:49 UTC, Denis-Tsyganok-Leasoft commented on src/Bankconfig/Bankconfig.php
> +      $link = 'https://www.afterpay.nl/en/about/pay-with-afterpay/payment-conditions';
looks like those links not bank functionality, but payment (afterpay) functionality, I'd suggest to move them to Helper or AfterPay class

2023-08-03 09:09 UTC, merged